version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Preparing Flask app for deployment"
      - mkdir output
      - cp main.py requirements.txt output/
      - cp -r .deployment output/   # If you need deployment configs
artifacts:
  files:
    - output/**/*
  discard-paths: yes
