version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Build phase - nothing to compile for Flask"
      - mkdir output
      - cp -r app.py requirements.txt output/
      - echo "Packaging Flask app"
artifacts:
  files:
    - output/**/*
  discard-paths: yes
