version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Preparing Flask app for deployment"
      - mkdir -p output
      - cp -r * output/   # Copy everything from root
      - ls -al output     # Debug: confirm files copied
artifacts:
  files:
    - output/**/*
  discard-paths: yes
