version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Preparing Flask app for deployment"
      - mkdir -p output
      - ls -al   # Debug: list files in root
      - cp main.py requirements.txt output/
      - ls -al output   # Debug: confirm files copied
      - if [ -d ".deployment" ]; then cp -r .deployment output/; fi
artifacts:
  files:
    - output/**/*
  discard-paths: yes
